project_id = "zkkcvjelobxdkavugpgt"

[functions.chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.fetch-youtube-thumbnails]
verify_jwt = true

[functions.fetch-channel-info]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false
